# Generated by Django 3.0.4 on 2020-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosuggestion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autosuggestion',
            name='keyword',
            field=models.CharField(max_length=100),
        ),
    ]
