# Generated by Django 3.0.4 on 2020-04-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_auto_20200422_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='all_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bullets',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='links',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
    ]
