# Generated by Django 3.0.4 on 2020-04-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_auto_20200422_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='all_images',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='bullets',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='links',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
