# Generated by Django 3.0.4 on 2020-04-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0010_auto_20200423_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='rating',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdescription',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
