# Generated by Django 3.0.4 on 2020-04-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0012_productlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='product_link_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
