# Generated by Django 3.0.4 on 2020-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0013_productdescription_product_link_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
